# Data Preprocessing(Veri Ön İşleme)

In [1]:
#kütüphaneler
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#veri yukleme
veriler=pd.read_csv("veriler.csv")

In [3]:
print(veriler)

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k


In [4]:
#veri on isleme
boy=veriler[["boy"]]
print(boy)

    boy
0   130
1   125
2   135
3   133
4   129
5   180
6   190
7   175
8   177
9   185
10  165
11  155
12  160
13  162
14  167
15  174
16  193
17  187
18  183
19  159
20  164
21  166


In [5]:
boykilo=veriler[["boy","kilo"]]
print(boykilo)

    boy  kilo
0   130    30
1   125    36
2   135    34
3   133    30
4   129    38
5   180    90
6   190    80
7   175    90
8   177    60
9   185   105
10  165    55
11  155    50
12  160    58
13  162    59
14  167    62
15  174    70
16  193    90
17  187    80
18  183    88
19  159    40
20  164    66
21  166    56


## Missing Values

In [6]:
eksikveriler=pd.read_csv("eksikveriler.csv")
print(eksikveriler)

   ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k


In [7]:
from sklearn.impute import SimpleImputer
 
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean',)
#iloc pandas kütüphanesinde hangi kolonları almamızı belirlediğimiz fonk.
Yas = veriler.iloc[:,1:4].values
print(Yas)

[[130  30  10]
 [125  36  11]
 [135  34  10]
 [133  30   9]
 [129  38  12]
 [180  90  30]
 [190  80  25]
 [175  90  35]
 [177  60  22]
 [185 105  33]
 [165  55  27]
 [155  50  44]
 [160  58  39]
 [162  59  41]
 [167  62  55]
 [174  70  47]
 [193  90  23]
 [187  80  27]
 [183  88  28]
 [159  40  29]
 [164  66  32]
 [166  56  42]]


In [8]:
imputer =imputer.fit(Yas[:,1:4])#: satır komple sütunda 1 ile 4
Yas[:,1:4]=imputer.transform(Yas[:,1:4])
print(Yas)

[[130  30  10]
 [125  36  11]
 [135  34  10]
 [133  30   9]
 [129  38  12]
 [180  90  30]
 [190  80  25]
 [175  90  35]
 [177  60  22]
 [185 105  33]
 [165  55  27]
 [155  50  44]
 [160  58  39]
 [162  59  41]
 [167  62  55]
 [174  70  47]
 [193  90  23]
 [187  80  27]
 [183  88  28]
 [159  40  29]
 [164  66  32]
 [166  56  42]]


## Kategorik Veriler

### Ordinal Veriler 

### Nominal Veriler 

## Sayısal Veriler 

### Oransal(Ratio) Veriler 

### Aralık(Interval) Veriler

In [9]:
#kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#kodlar
#veri yukleme

veriler = pd.read_csv('eksikveriler.csv')
#pd.read_csv("veriler.csv")
print(veriler)


#eksik veriler
#sci - kit learn
from sklearn.impute import SimpleImputer
 
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
#iloc pandas kütüphanesinde hangi kolonları almamızı belirlediğimiz fonk.
Yas = veriler.iloc[:,1:4].values

imputer =imputer.fit(Yas[:,1:4])#: satır komple sütunda 1 ile 4
Yas[:,1:4]=imputer.transform(Yas[:,1:4])
print(Yas)



ulke = veriler.iloc[:,0:1].values
print(ulke)
from sklearn.preprocessing import LabelEncoder#her bir değer için sayısal değer 
le = LabelEncoder()
ulke[:,0] = le.fit_transform(ulke[:,0])#hem uygula hem de işle
print(ulke)

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categories="auto")
ulke=ohe.fit_transform(ulke).toarray()
print(ulke)

   ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k
[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [

## Verilerin Birleştirilmesi ve DataFrame Oluşturulması 

In [10]:
sonuc=pd.DataFrame(data=ulke,index=range(22),columns=["fr","tr","us"])
print(sonuc)

     fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0


In [11]:
print(Yas)

[[130.    30.    10.  ]
 [125.    36.    11.  ]
 [135.    34.    10.  ]
 [133.    30.     9.  ]
 [129.    38.    12.  ]
 [180.    90.    30.  ]
 [190.    80.    25.  ]
 [175.    90.    35.  ]
 [177.    60.    22.  ]
 [185.   105.    33.  ]
 [165.    55.    27.  ]
 [155.    50.    44.  ]
 [160.    58.    28.45]
 [162.    59.    41.  ]
 [167.    62.    55.  ]
 [174.    70.    47.  ]
 [193.    90.    28.45]
 [187.    80.    27.  ]
 [183.    88.    28.  ]
 [159.    40.    29.  ]
 [164.    66.    32.  ]
 [166.    56.    42.  ]]


In [12]:
sonuc2=pd.DataFrame(data=Yas,index=range(22),columns=["boy","kilo","yaş"])
print(sonuc2)

      boy   kilo    yaş
0   130.0   30.0  10.00
1   125.0   36.0  11.00
2   135.0   34.0  10.00
3   133.0   30.0   9.00
4   129.0   38.0  12.00
5   180.0   90.0  30.00
6   190.0   80.0  25.00
7   175.0   90.0  35.00
8   177.0   60.0  22.00
9   185.0  105.0  33.00
10  165.0   55.0  27.00
11  155.0   50.0  44.00
12  160.0   58.0  28.45
13  162.0   59.0  41.00
14  167.0   62.0  55.00
15  174.0   70.0  47.00
16  193.0   90.0  28.45
17  187.0   80.0  27.00
18  183.0   88.0  28.00
19  159.0   40.0  29.00
20  164.0   66.0  32.00
21  166.0   56.0  42.00


In [13]:
cinsiyet=veriler.iloc[:,-1:].values
print(cinsiyet)

[['e']
 ['e']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['k']
 ['k']]


In [14]:
sonuc3=pd.DataFrame(data=cinsiyet, index=range(22),columns=["cinsiyet"])
print(sonuc3)

   cinsiyet
0         e
1         e
2         k
3         k
4         e
5         e
6         e
7         e
8         k
9         e
10        k
11        k
12        k
13        k
14        k
15        e
16        e
17        e
18        e
19        k
20        k
21        k


In [15]:
#frame leri birleştirme
s=pd.concat([sonuc,sonuc2],axis=1)
print(s)

     fr   tr   us    boy   kilo    yaş
0   0.0  1.0  0.0  130.0   30.0  10.00
1   0.0  1.0  0.0  125.0   36.0  11.00
2   0.0  1.0  0.0  135.0   34.0  10.00
3   0.0  1.0  0.0  133.0   30.0   9.00
4   0.0  1.0  0.0  129.0   38.0  12.00
5   0.0  1.0  0.0  180.0   90.0  30.00
6   0.0  1.0  0.0  190.0   80.0  25.00
7   0.0  1.0  0.0  175.0   90.0  35.00
8   0.0  1.0  0.0  177.0   60.0  22.00
9   0.0  0.0  1.0  185.0  105.0  33.00
10  0.0  0.0  1.0  165.0   55.0  27.00
11  0.0  0.0  1.0  155.0   50.0  44.00
12  0.0  0.0  1.0  160.0   58.0  28.45
13  0.0  0.0  1.0  162.0   59.0  41.00
14  0.0  0.0  1.0  167.0   62.0  55.00
15  1.0  0.0  0.0  174.0   70.0  47.00
16  1.0  0.0  0.0  193.0   90.0  28.45
17  1.0  0.0  0.0  187.0   80.0  27.00
18  1.0  0.0  0.0  183.0   88.0  28.00
19  1.0  0.0  0.0  159.0   40.0  29.00
20  1.0  0.0  0.0  164.0   66.0  32.00
21  1.0  0.0  0.0  166.0   56.0  42.00


In [16]:
s2=pd.concat([sonuc,sonuc2,sonuc3],axis=1)
print(s2)

     fr   tr   us    boy   kilo    yaş cinsiyet
0   0.0  1.0  0.0  130.0   30.0  10.00        e
1   0.0  1.0  0.0  125.0   36.0  11.00        e
2   0.0  1.0  0.0  135.0   34.0  10.00        k
3   0.0  1.0  0.0  133.0   30.0   9.00        k
4   0.0  1.0  0.0  129.0   38.0  12.00        e
5   0.0  1.0  0.0  180.0   90.0  30.00        e
6   0.0  1.0  0.0  190.0   80.0  25.00        e
7   0.0  1.0  0.0  175.0   90.0  35.00        e
8   0.0  1.0  0.0  177.0   60.0  22.00        k
9   0.0  0.0  1.0  185.0  105.0  33.00        e
10  0.0  0.0  1.0  165.0   55.0  27.00        k
11  0.0  0.0  1.0  155.0   50.0  44.00        k
12  0.0  0.0  1.0  160.0   58.0  28.45        k
13  0.0  0.0  1.0  162.0   59.0  41.00        k
14  0.0  0.0  1.0  167.0   62.0  55.00        k
15  1.0  0.0  0.0  174.0   70.0  47.00        e
16  1.0  0.0  0.0  193.0   90.0  28.45        e
17  1.0  0.0  0.0  187.0   80.0  27.00        e
18  1.0  0.0  0.0  183.0   88.0  28.00        e
19  1.0  0.0  0.0  159.0   40.0  29.00  

# Veri Kümesinin Eğitim ve Test Olarak Bölünmesi

In [17]:
from sklearn.model_selection import train_test_split #train test split olarak bölüyoruz
x_train,x_test,y_train,y_test=train_test_split(s,sonuc3,test_size=0.33,random_state=0) #train -s test- sonuc3

In [18]:
print(x_train)

     fr   tr   us    boy   kilo    yaş
8   0.0  1.0  0.0  177.0   60.0  22.00
6   0.0  1.0  0.0  190.0   80.0  25.00
16  1.0  0.0  0.0  193.0   90.0  28.45
4   0.0  1.0  0.0  129.0   38.0  12.00
2   0.0  1.0  0.0  135.0   34.0  10.00
5   0.0  1.0  0.0  180.0   90.0  30.00
17  1.0  0.0  0.0  187.0   80.0  27.00
9   0.0  0.0  1.0  185.0  105.0  33.00
7   0.0  1.0  0.0  175.0   90.0  35.00
18  1.0  0.0  0.0  183.0   88.0  28.00
3   0.0  1.0  0.0  133.0   30.0   9.00
0   0.0  1.0  0.0  130.0   30.0  10.00
15  1.0  0.0  0.0  174.0   70.0  47.00
12  0.0  0.0  1.0  160.0   58.0  28.45


In [19]:
print(y_train)

   cinsiyet
8         k
6         e
16        e
4         e
2         k
5         e
17        e
9         e
7         e
18        e
3         k
0         e
15        e
12        k


In [20]:
print(x_test)

     fr   tr   us    boy  kilo   yaş
20  1.0  0.0  0.0  164.0  66.0  32.0
10  0.0  0.0  1.0  165.0  55.0  27.0
14  0.0  0.0  1.0  167.0  62.0  55.0
13  0.0  0.0  1.0  162.0  59.0  41.0
1   0.0  1.0  0.0  125.0  36.0  11.0
21  1.0  0.0  0.0  166.0  56.0  42.0
11  0.0  0.0  1.0  155.0  50.0  44.0
19  1.0  0.0  0.0  159.0  40.0  29.0


In [21]:
print(y_test)

   cinsiyet
20        k
10        k
14        k
13        k
1         e
21        k
11        k
19        k


## Öznitelik Ölçekleme(Feature Scaling) 

In [22]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.fit_transform(x_test)

In [23]:
pd.DataFrame(X_train)

0         1         2         3         4         5
0  -0.632456  0.866025 -0.408248  0.450494 -0.296579 -0.247171
1  -0.632456  0.866025 -0.408248  1.008249  0.509655  0.034162
2   1.581139 -1.154701 -0.408248  1.136962  0.912772  0.357695
3  -0.632456  0.866025 -0.408248 -1.608909 -1.183436 -1.184949
4  -0.632456  0.866025 -0.408248 -1.351483 -1.344683 -1.372504
5  -0.632456  0.866025 -0.408248  0.579207  0.912772  0.503051
6   1.581139 -1.154701 -0.408248  0.879537  0.509655  0.221717
7  -0.632456 -1.154701  2.449490  0.793728  1.517447  0.784384
8  -0.632456  0.866025 -0.408248  0.364686  0.912772  0.971939
9   1.581139 -1.154701 -0.408248  0.707920  0.832148  0.315495
10 -0.632456  0.866025 -0.408248 -1.437292 -1.505929 -1.466282
11 -0.632456  0.866025 -0.408248 -1.566004 -1.505929 -1.372504
12  1.581139 -1.154701 -0.408248  0.321782  0.106538  2.097272
13 -0.632456 -1.154701  2.449490 -0.278878 -0.377202  0.357695

In [24]:
pd.DataFrame(X_test)

0         1    2         3         4         5
0  1.290994 -0.377964 -1.0  0.472400  1.328538 -0.249913
1 -0.774597 -0.377964  1.0  0.549527  0.204390 -0.649773
2 -0.774597 -0.377964  1.0  0.703780  0.919757  1.589444
3 -0.774597 -0.377964  1.0  0.318147  0.613171  0.469836
4 -0.774597  2.645751 -1.0 -2.535536 -1.737319 -1.929325
5  1.290994 -0.377964 -1.0  0.626653  0.306586  0.549808
6 -0.774597 -0.377964  1.0 -0.221739 -0.306586  0.709752
7  1.290994 -0.377964 -1.0  0.086767 -1.328538 -0.489829