# Çoklu Doğrusal Regresyon(Multiple Linear Regression)

### Basit Doğrusal Regresyon Örneği 

### Çoklu Doğrusal Regresyon Örneği

## Kukla Değişken (Dummy Variable) 

## Olasılık Değeri(P-Value) 

### Çok Değişkenli Modellerde, Değişken Seçimi 

### Bütün Değişkenler

### Geriye Doğru Eleme(Backward Elimination) 

### İleriye Seçim(Forward Selection) 

### Çift Yönlü Eleme(Bidirecitonal Elimination)

### Bütün Yöntemler 

## Çoklu Değişken İçin Veri Hazırlama

In [5]:
#1. kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#2. Veri Onisleme

#2.1. Veri Yukleme
veriler = pd.read_csv('veriler.csv')
#pd.read_csv("veriler.csv")


#veri on isleme


Yas = veriler.iloc[:,1:4].values


#encoder:  Kategorik -> Numeric
ulke = veriler.iloc[:,0:1].values
print(ulke)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ulke[:,0] = le.fit_transform(ulke[:,0])
print(ulke)

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categories="auto")
ulke=ohe.fit_transform(ulke).toarray()
print(ulke)

c = veriler.iloc[:,-1:].values
print(c)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
c[:,0] = le.fit_transform(c[:,0])
print(c)

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categories="auto")
c=ohe.fit_transform(c).toarray()
print(c)



#numpy dizileri dataframe donusumu
sonuc = pd.DataFrame(data = ulke, index = range(22), columns=['fr','tr','us'] )
print(sonuc)

sonuc2 =pd.DataFrame(data = Yas, index = range(22), columns = ['boy','kilo','yas'])
print(sonuc2)

cinsiyet = veriler.iloc[:,-1].values
print(cinsiyet)

sonuc3 = pd.DataFrame(data = c[:,:1] , index=range(22), columns=['cinsiyet'])
print(sonuc3)

#dataframe birlestirme islemi
s=pd.concat([sonuc,sonuc2],axis=1)
print(s)

s2= pd.concat([s,sonuc3],axis=1)
print(s2)

#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(s,sonuc3,test_size=0.33, random_state=0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

[['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['tr']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['us']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']
 ['fr']]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[['e']
 ['e']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['k']
 ['k']]
[[0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]]
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 

LinearRegression()

In [6]:
#1. kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#2. Veri Onisleme

#2.1. Veri Yukleme
veriler = pd.read_csv('veriler.csv')
#pd.read_csv("veriler.csv")


#veri on isleme


Yas = veriler.iloc[:,1:4].values


#encoder:  Kategorik -> Numeric
ulke = veriler.iloc[:,0:1].values

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ulke[:,0] = le.fit_transform(ulke[:,0])


from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categories="auto")
ulke=ohe.fit_transform(ulke).toarray()


c = veriler.iloc[:,-1:].values

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
c[:,0] = le.fit_transform(c[:,0])


from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categories="auto")
c=ohe.fit_transform(c).toarray()




#numpy dizileri dataframe donusumu
sonuc = pd.DataFrame(data = ulke, index = range(22), columns=['fr','tr','us'] )


sonuc2 =pd.DataFrame(data = Yas, index = range(22), columns = ['boy','kilo','yas'])


cinsiyet = veriler.iloc[:,-1].values


sonuc3 = pd.DataFrame(data = c[:,:1] , index=range(22), columns=['cinsiyet'])


#dataframe birlestirme islemi
s=pd.concat([sonuc,sonuc2],axis=1)


s2= pd.concat([s,sonuc3],axis=1)

#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(s,sonuc3,test_size=0.33, random_state=0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)


y_pred = regressor.predict(x_test)



In [7]:
#1. kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#2. Veri Onisleme

#2.1. Veri Yukleme
veriler = pd.read_csv('veriler.csv')
#pd.read_csv("veriler.csv")


#veri on isleme


Yas = veriler.iloc[:,1:4].values


#encoder:  Kategorik -> Numeric
ulke = veriler.iloc[:,0:1].values

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ulke[:,0] = le.fit_transform(ulke[:,0])


from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categories="auto")
ulke=ohe.fit_transform(ulke).toarray()


c = veriler.iloc[:,-1:].values

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
c[:,0] = le.fit_transform(c[:,0])


from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categories="auto")
c=ohe.fit_transform(c).toarray()




#numpy dizileri dataframe donusumu
sonuc = pd.DataFrame(data = ulke, index = range(22), columns=['fr','tr','us'] )


sonuc2 =pd.DataFrame(data = Yas, index = range(22), columns = ['boy','kilo','yas'])


cinsiyet = veriler.iloc[:,-1].values


sonuc3 = pd.DataFrame(data = c[:,:1] , index=range(22), columns=['cinsiyet'])


#dataframe birlestirme islemi
s=pd.concat([sonuc,sonuc2],axis=1)


s2= pd.concat([s,sonuc3],axis=1)

#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(s,sonuc3,test_size=0.33, random_state=0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)


y_pred = regressor.predict(x_test)

boy=s2.iloc[:,3:4].values
print(boy)

sol=s2.iloc[:,:3]
sag=s2.iloc[:,4:]

veri=pd.concat([sol,sag],axis=1)

print(veri)

x_train, x_test,y_train,y_test = train_test_split(veri,boy,test_size=0.33, random_state=0)

r2=LinearRegression()
r2.fit(x_train,y_train)

y_pred=r2.predict(x_test)

print(y_pred)
print(y_test)

[[130]
 [125]
 [135]
 [133]
 [129]
 [180]
 [190]
 [175]
 [177]
 [185]
 [165]
 [155]
 [160]
 [162]
 [167]
 [174]
 [193]
 [187]
 [183]
 [159]
 [164]
 [166]]
     fr   tr   us  kilo  yas  cinsiyet
0   0.0  1.0  0.0    30   10       1.0
1   0.0  1.0  0.0    36   11       1.0
2   0.0  1.0  0.0    34   10       0.0
3   0.0  1.0  0.0    30    9       0.0
4   0.0  1.0  0.0    38   12       1.0
5   0.0  1.0  0.0    90   30       1.0
6   0.0  1.0  0.0    80   25       1.0
7   0.0  1.0  0.0    90   35       1.0
8   0.0  1.0  0.0    60   22       0.0
9   0.0  0.0  1.0   105   33       1.0
10  0.0  0.0  1.0    55   27       0.0
11  0.0  0.0  1.0    50   44       0.0
12  0.0  0.0  1.0    58   39       0.0
13  0.0  0.0  1.0    59   41       0.0
14  0.0  0.0  1.0    62   55       0.0
15  1.0  0.0  0.0    70   47       1.0
16  1.0  0.0  0.0    90   23       1.0
17  1.0  0.0  0.0    80   27       1.0
18  1.0  0.0  0.0    88   28       1.0
19  1.0  0.0  0.0    40   29       0.0
20  1.0  0.0  0.0    66   

## Python ile Geri Eleme(Backward Elimination)

In [8]:
import statsmodels.api as sm 
#bir dizi oluşturup sırayla değişkenleri eleyeceğiz,hangisinin daha etkili oldugunu göreceğiz
X = np.append(arr = np.ones((22,1)).astype(int), values=veri, axis=1 )#en başa birlerden oluşan dizi eklendi
X_l = veri.iloc[:,[0,1,2,3,4,5]].values
r_ols = sm.OLS(endog = boy, exog =X_l)#endog bağımlı değişken,exog bağımsız değişken
r = r_ols.fit()
print(r.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Mon, 07 Sep 2020   Prob (F-statistic):           5.41e-07
Time:                        17:51:50   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           114.0688      8.145     14.005      0.0

In [9]:
import statsmodels.api as sm 
#bir dizi oluşturup sırayla değişkenleri eleyeceğiz,hangisinin daha etkili oldugunu göreceğiz
X = np.append(arr = np.ones((22,1)).astype(int), values=veri, axis=1 )#en başa birlerden oluşan dizi eklendi
X_l = veri.iloc[:,[0,1,2,3,5]].values
r_ols = sm.OLS(endog = boy, exog =X_l)#endog bağımlı değişken,exog bağımsız değişken
r = r_ols.fit()
print(r.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.884
Model:                            OLS   Adj. R-squared:                  0.857
Method:                 Least Squares   F-statistic:                     32.47
Date:                Mon, 07 Sep 2020   Prob (F-statistic):           9.32e-08
Time:                        17:51:54   Log-Likelihood:                -74.043
No. Observations:                  22   AIC:                             158.1
Df Residuals:                      17   BIC:                             163.5
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           115.6583      6.734     17.175      0.0