# Karar Ağacı ile Sınıflandırma (Decision Tree)

In [2]:
#Kütüphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#veri yükleme
veriler=pd.read_csv("veriler.csv")

x=veriler.iloc[:,1:4].values #bağımsız değişkenler(boy,kilo ve yaş)
y=veriler.iloc[:,-1:].values #bağımlı değişkenler(cinsiyet)



#boy kilo ve yaştan cinsiyet bulmaya çalışan program

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0)


from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.transform(x_test)

from sklearn.linear_model import LogisticRegression
logr= LogisticRegression(random_state=0)
logr.fit(X_train,y_train)

y_pred=logr.predict(X_test)

#print("tahminler:",y_pred)
#print("sonuclar:",y_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
#print("confusion matrix:\n",cm)

from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier(n_neighbors=5,metric="minkowski")

knn.fit(X_train,y_train)

y_pred_knn=knn.predict(X_test)

cm2=confusion_matrix(y_test, y_pred)

#print(cm2)

from sklearn.svm import SVC
svc=SVC(kernel="linear")
svc.fit(X_train,y_train)

y_pred=svc.predict(X_test)

cm3=confusion_matrix(y_test, y_pred)

#print("svm:",cm3)


from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train,y_train)

y_pred=gnb.predict(X_test)
cm4=confusion_matrix(y_test, y_pred)
#print("GNB",cm4)

from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(criterion="entropy")

dtc.fit(X_train,y_train)
y_pred=dtc.predict(X_test)

cm5=confusion_matrix(y_test, y_pred)
print("DTC:")
print(cm5)

/home/onur/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


DTC:
[[1 0]
 [1 6]]


<ipython-input-2-0f38deddb36b>:42: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(X_train,y_train)
/home/onur/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/home/onur/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


# Rassal Ağaçlar İle Sınıflandırma (Random Forest)

In [3]:
#Kütüphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#veri yükleme
veriler=pd.read_csv("veriler.csv")

x=veriler.iloc[:,1:4].values #bağımsız değişkenler(boy,kilo ve yaş)
y=veriler.iloc[:,-1:].values #bağımlı değişkenler(cinsiyet)



#boy kilo ve yaştan cinsiyet bulmaya çalışan program

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0)


from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.transform(x_test)

from sklearn.linear_model import LogisticRegression
logr= LogisticRegression(random_state=0)
logr.fit(X_train,y_train)

y_pred=logr.predict(X_test)

#print("tahminler:",y_pred)
#print("sonuclar:",y_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
#print("confusion matrix:\n",cm)

from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier(n_neighbors=5,metric="minkowski")

knn.fit(X_train,y_train)

y_pred_knn=knn.predict(X_test)

cm2=confusion_matrix(y_test, y_pred)

#print(cm2)

from sklearn.svm import SVC
svc=SVC(kernel="linear")
svc.fit(X_train,y_train)

y_pred=svc.predict(X_test)

cm3=confusion_matrix(y_test, y_pred)

#print("svm:",cm3)


from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train,y_train)

y_pred=gnb.predict(X_test)
cm4=confusion_matrix(y_test, y_pred)
#print("GNB",cm4)

from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(criterion="entropy")

dtc.fit(X_train,y_train)
y_pred=dtc.predict(X_test)

cm5=confusion_matrix(y_test, y_pred)
#print("DTC:")
#print(cm5)

from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=10,criterion="entropy")
rfc.fit(X_train,y_train)

y_pred=rfc.predict(X_test)

cm6=confusion_matrix(y_test, y_pred)
print("RFC:")
print(cm6)

/home/onur/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
<ipython-input-3-e9f022b27063>:42: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(X_train,y_train)
/home/onur/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/home/onur/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


RFC:
[[1 0]
 [1 6]]


<ipython-input-3-e9f022b27063>:81: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc.fit(X_train,y_train)


# Accuracy, ROC eğrisi ve AUC değeri

## Accuracy Paradox (Doğruluk Paradoksu) 

## ROC Curve(Receiver Operating Characteristic Curve - Alıcı İşletim Karakteristik Eğrisi) 

In [4]:
#1. kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix

#2. Veri Onisleme

#2.1. Veri Yukleme
veriler = pd.read_csv('veriler.csv')
#pd.read_csv("veriler.csv")

x = veriler.iloc[:,1:4].values #bağımsız değişkenler
y = veriler.iloc[:,4:].values #bağımlı değişken
print(y)

#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=0)

#verilerin olceklenmesi
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

# Buradan itibaren sınıflandırma algoritmaları başlar
# 1. Logistic Regression

from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(random_state=0)
logr.fit(X_train,y_train) #egitim

y_pred = logr.predict(X_test) #tahmin
print(y_pred)
print(y_test)

#karmasiklik matrisi
cm = confusion_matrix(y_test,y_pred)
print(cm)


# 2. KNN

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1, metric='minkowski')
knn.fit(X_train,y_train)

y_pred = knn.predict(X_test)

cm = confusion_matrix(y_test,y_pred)
print(cm)

# 3. SVC (SVM classifier)
from sklearn.svm import SVC
svc = SVC(kernel='poly')
svc.fit(X_train,y_train)

y_pred = svc.predict(X_test)

cm = confusion_matrix(y_test,y_pred)
print('SVC')
print(cm)

# 4. Naive Bayes
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_test)

cm = confusion_matrix(y_test,y_pred)
print('GNB')
print(cm)

# 5. Decision tree
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = 'entropy')

dtc.fit(X_train,y_train)
y_pred = dtc.predict(X_test)

cm = confusion_matrix(y_test,y_pred)
print('DTC')
print(cm)

# 6. Random Forest
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=10, criterion = 'entropy')
rfc.fit(X_train,y_train)

y_pred = rfc.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
print('RFC')
print(cm)


# 7. ROC , TPR, FPR değerleri 

y_proba = rfc.predict_proba(X_test)
print(y_test)
print(y_proba[:,0])

from sklearn import metrics
fpr , tpr , thold = metrics.roc_curve(y_test,y_proba[:,0],pos_label='e')
print(fpr)
print(tpr)


[['e']
 ['e']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['e']
 ['e']
 ['e']
 ['k']
 ['k']
 ['k']]
['e' 'e' 'e' 'e' 'k' 'e' 'e' 'e']
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]
[[0 1]
 [7 0]]
[[1 0]
 [1 6]]
SVC
[[1 0]
 [7 0]]
GNB
[[0 1]
 [6 1]]
DTC
[[1 0]
 [1 6]]
RFC
[[1 0]
 [1 6]]
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]
[0.6 0.2 0.3 0.2 0.9 0.2 0.3 0.4]
[0.         0.         0.28571429 0.57142857 1.        ]
[0. 1. 1. 1. 1.]


/home/onur/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
<ipython-input-4-76958683a2e4>:49: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  knn.fit(X_train,y_train)
/home/onur/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
/home/onur/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
<ipython